### ISSUE TITLE
Improper Code

### ISSUE THREAD

**Issue by kellian-cottart** [Erzangel/ehps-backend#1]
# Improper code

I daresay that I'm sorry to infringe my will upon you. However, it seems that you haven't coded properly.

## Description
I've seen you using `javascript`. Henceforth, you need to take a step back and assess the situation carefully. Why are you not using `coffeescript` which is morbinfinitely better than the peepo `javascript`?

You need to know that `coffeescript` is a transpiled version of `javascript` that allows for cleaner code and a better functional approach. This is the official [coffeescript link](https://coffeescript.org/), from which I hope you will learn from your mistakes and start coding like a real chad.

Best regards, K.

**Comment by Erzangel** [comment]
# Disclaimer

**If anybody I am professionally associated with in the foreseeable future sees this, I'd like to introduce you to my dear friend Kellian**. 

He's the smartest guy I know, a real pleasure to work with, and as you can obviously see from the above post, he's fun at parties. A "real one", if you will. If you have the chance to get to work with him in the future, we can all have a drink together. I cannot guarantee his sense of humor is keeping up with latest trends however, as using "morb" in words is no longer funny to anyone except me.

## Proper answer to the issue

Now, to properly respond and still comply with the GitHub guidelines, I will put it this way: this issue is the equivalent of walking up to someone in the street and telling them they are ugly. 

Now, I believe this is a form of natural selection. Considering my facial structure is unfortunately harder to correct than my coding habits (we do not have linters for the former), I am thankful this is the better one of the two scenarios. Given this lifechanging revelation you have presented me, I will now formerly apologize and swear to never do filthy JavaScript ever again. But we can all be glad this is not a PHP app.

## Real proper answer to the issue

tbh I needed a functional backend for a student project and recycled an old [express.js](https://expressjs.com/) project to get a DB working quickly. It could have been JavaScript, CoffeeScript, TypeScript, PureScript or [JSFuck](https://en.wikipedia.org/wiki/JSFuck), really.

## Conclusion

Of course, the entirety of this response is done jokingly and with the intent of making my colleague or anyone wicked enough to stumble upon this smirk a good smile. 

Oh, by the way @kellianoy, it is spelled *infringe*, not *hinfringe*.
